version: "3"
services:
  db_didi_test:
    image: postgres:13
    container_name: db_didi_test
    restart: always #container reinicia se morrer
    ports:
      - 1345:5432
    env_file:
      - .env.test #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    volumes:
      - db_github:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: . #Dockerfile do node se encontra na pasta atual
    ports:
      - 5001:5000
    depends_on:
      - db_didi_test # sรณ sobe quando o postgres tiver no ar
    env_file:
      - .env #configurar DATABASE_URL

volumes:
  db_github: