name: Deploy no Heroku
on:
  push:
    branches:
      - main
jobs:
  HerokuDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o codigo do repositorio
        uses: actions/checkout@v3
      - name: Deploy do app no heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API }}
          heroku_app_name: ${{ secrets.HEROKU_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: "main"
