name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students__tests"
          envkey_POSTGRES_URL: "postgresql://postgres:postgres@db_didi_test:5432/students__tests"
          file_name: .env
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app npm run test